language: python
python:
  - "3.6"
cache:
 directories:
   # - $HOME/.cache/pip
   # - $HOME/.npm
   # - node_modules

before_install:
- set -e
- . $HOME/.nvm/nvm.sh
- nvm ls
# - nvm install 14.9.0 -v
# - nvm use 14.9.0
- nvm use stable
- rm -rf node_modules
- npm install
- git checkout package.json package-lock.json
- sudo apt-get install python3-pip
- python3 --version
- python2 --version
- pip3 --version
- sudo -H pip install --upgrade setuptools
- sudo -H pip install --upgrade pip wheel requests pyopenssl
- sudo -H pip install --ignore-installed six
- sudo -H pip install --upgrade tox twine
- pip install --upgrade setuptools
- pip install --upgrade aiohttp requests cryptography pyopenssl
- pip2 install requests[security]
- git pull --tags
script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then npm config set git-tag-version=false && NPM_VERSION=$(npm version patch); fi
- npm run build
- cd python
- tox -e doc
- cd ..
- npm run test-base
- bash -c 'node run-tests --js --python-async 5' 2>&1
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then env COMMIT_MESSAGE=${NPM_VERSION:1} GITHUB_TOKEN=${GITHUB_TOKEN} ./build/push.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then cd python && env PYPI_PASSWORD=${PYPI_PASSWORD} ./deploy.sh && cd ..; fi
after_failure:
- dmesg | grep -i kill
deploy:
  - provider: npm
    email: igor.kroitor@gmail.com
    api_key:
      secure: N76dtlNP0Q9sKDw8brbckPU2evN2anVb3G8aLM0u9PzY7WOLahSdghQUeU+xVZ7Qw0zqaThPPYpR0dacj4POUjd9UsjBl8ROTsUSjjSbM4C/Im+6sSqyO5Bl+9ZDy7xNvx92KnsQaGnvdd1NHHcL+ruyiFPzBpjYY3c4gp5jEe+vPKj9uSlT0UsLbtARCDi4MmYHCSSI+KAw2E0qo/RVQM07SEAUPLHvE17jjDr3IMomeFEP9uC36I1T7xM+nlfw08lAUb12nfS5PYMNBlLboC2v8/t20+ulKvNCPvRFyBmzw2sRzBMcE6XLfk0+1ajREjwU+n6lx6+63YIJYo5YAlG5hCBF2mmaLRSXfDTSg0khv7MID3OZwBmJ+bozrQwhXb9dYK1gpELuxDOaUu5xSn1lJGjx4JtH2wdIkxYoAgX/Gqx9xrjA5KnKdx/YhJwgLPYBFgN6pgqufA5Vu6JDQ0yd9qsU8qnXRH9jLNhsCy15fKCxcdSHK+eib+inRg/ayAqFYaRpugndiww5D3skNKyBFBXxuU1F7EXloiTy+dz2RR6vF08OSflxW4CGgSBtaugQIEG7XO3UjSL9sSj96dpBnTIRSRXtC4PvEPRtEWP6xDarYx7yl+mpuSryHyx+j6E23XpNHEM+KA7Ps1xv6F46yE0D9eNRNrp82XPFt6A=
env:
  global:
    secure: CQBKPcipKTvfgBi8KXaJ6KyjJL5GcWPEW7WrKZcTeM2AaNqTX8w3yuqjsezxVnQWLG3TzEI0m1K31Fv9wfZHsMwRIr5py6AeAc4C2JgaKs3FSAFJ3m46a9hK7FIeC0xMdXszPJx7534XiuG8nMJRbwbNNswb35GekysKU87g5Sf6U7UFFeyyyQdchiPF85lYBt/AJSArNsfHMd0RKQY5pHdAHNNB70qFECIBeC6MYiUFBHydw2ist/bSWa9GYEh3LxUNMQ7bbxuzD6+sVMU2PW61gEpa3I9HB7NTQvPp+YbYWqBwS++SKCuqkalXdMPeCIINu64T1UtFGZNWvw9xfg8T8GwGHwZnNZ1o3WCXKo9/+FC70OAb76mblEXllhQs+gBL5g/bqdQBKfGrYIACHBRE3pzNPSRn7oY3hpk7NLoJRbB28OQ5ymJrDc8hctoXwgD3KrIM91+6YqycOifidLFHecg/VA2bjSx/ql69sVhNchaBJ8b7EMMIjo1DrFIv43XJ7DHX+2yZFJD8uv5eCGHkfXv6XfV5312TYzGYsxpfJ9my9tdTGxop2BXzaf1nYqrI+RPKIZrh6FgiXgRaetwRpWl4G+DqxKbKtfzYlZtYU2JeJ7Z5AMwLHyvxxcuOH3MrE+vk5nbU5gE9E3m5o7yH+d7Qj5liCyXk0zxijn0=
